version: "2"

run:
  timeout: 10m
  allow-parallel-runners: true
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    - cyclop
    - goconst
    - testifylint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocritic
    - godot
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    # Note: gosimple, stylecheck, tenv are deprecated/merged in v2
    # gosimple -> staticcheck (included)
    # stylecheck -> staticcheck (included)
    # tenv -> usetesting (use instead if needed)
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    govet:
      disable:
        - fieldalignment
    revive:
      rules:
        - name: unexported-return
          disabled: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - commentedOutCode
    errcheck:
      check-type-assertions: true
      check-blank: true
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: camel
          bson: camel
          avro: snake
          mapstructure: kebab
    cyclop:
      max-complexity: 25

formatters:
  enable:
    - gofmt
    - goimports
